### ISSUE TITLE
@jvcasillas

### ISSUE THREAD

**Issue by IvanAndreuRascon** [IvanAndreu/pa_4#1]

**Comment by jvcasillas** [comment]
|                 Task                                              | Points | Points earned |
| :---------------------------------------------------------------- | -----: | ------------: |
| Fork the `pa_4` repo                                              |    0.5 | 0.5 |
| Correctly segment items                                           |      2 | 2 |
| Fix scripts and extract data                                      |      2 | 2 |
| Generate a hypothesis                                             |    0.5 | 0.5 |
| Calculate descriptives for VOT, present them in a table           |      1 | 1 |
| Plot VOT                                                          |      1 | 1 |
| Include figure(s) of the acoustic data                            |    0.5 | 0.5 |
| Evaluate your hypothesis                                          |    0.5 | 0.5 |
| Write a reproducible report                                       |      1 | 1 |
| Knit the reproducible report                                      |      1 | 1 |
| **Total**                                                         |     10 | 10 |

Buen trabajo. No se me había ocurrido usar estos datos para mirar F1/F2 como en Bradlow. Interesante.
